version: "3.7"

##############
#
# Para configurar o chatwoot, execute o comando abaixo no console do container:
#
# bundle exec rails db:chatwoot_prepare
#
# Variáveis de Ambiente:
#
# https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables
#
# Valores Padrão:
# https://github.com/chatwoot/chatwoot/blob/develop/.env.example
#
#############

# Definição dos Serviços
services:
  # Definição do Nome do Serviço da Interface Web
  chatwoot_api:
    # imagem oficial do chatwoot
    image: chatwoot/chatwoot:latest
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # comando padrão para subir o servidor web
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    # entrypoint para configurar o aplicativo
    entrypoint: docker/entrypoints/rails.sh
    # configura os volumes do chatwoot
    volumes:
      - chatwoot_data:/app/storage # arquivos do usuário
    # configura a rede do serviço
    networks:
      # Define a nossa rede padrão do swarm
      - network_swarm_public
    # Configura as variáveis de ambiente do chatwoot
    environment:

    # Configura o Modo de Deploy da Aplicação
    deploy:
      # Configura o modo de deploy
      mode: replicated
      # Configura o numero de replicas
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:
          # Define a quantidade de CPU para o CodeChat para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o CodeChat para evitar travamento do Host
          memory: 1024M
      labels:
        # Configura o Roteamento do Traefik
        - traefik.enable=true # habilita o traefik
        # Configura o Roteamento do Traefik para o Chatwoot
        - traefik.http.routers.chatwoot_api.rule=(Host(`atendimento.luizeof.dev`) && PathPrefix(`/api/v1`))
        # Define o tipo de entrada para HTTPS
        - traefik.http.routers.chatwoot_api.entrypoints=websecure
        # Define o certificado
        - traefik.http.routers.chatwoot_api.tls.certresolver=letsencryptresolver
        # Define o serviço do Chatwoot
        - traefik.http.routers.chatwoot_api.service=chatwoot_api
        # Define a porta do Chatwoot
        - traefik.http.services.chatwoot_api.loadbalancer.server.port=3000
        # Define os Headers do Chatwoot
        - traefik.http.services.chatwoot_api.loadbalancer.passhostheader=true
        # Configura o Middleware do Traefik para trabalhar com SSL no Websockets
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_api.middlewares=sslheader@docker
volumes:
  chatwoot_data:
    external: true
    name: chatwoot_data
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
