version: "3.7"

services:
  # Define o serviço do Metabase
  metabase:
    # Define a imagem do Metabase
    # https://hub.docker.com/r/metabase/metabase/tags
    image: metabase/metabase:v0.50.21.2
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # Define o entrypoint para configuração do Metabase
    entrypoint: /app/run_metabase.sh
    # Define a rede que o container vai utilizar
    networks:
      - network_swarm_public
    # Define as variáveis de Ambiente do Metabase
    environment:
      # Configura o tipo do Banco de Dados
      - MB_DB_TYPE=postgres
      # Configura o Nome do Banco de Dados
      - MB_DB_DBNAME=metabase
      # Configura o Host do Banco de Dados
      - MB_DB_HOST=postgres
      # Configura a Porta do Banco de Dados
      - MB_DB_PORT=5432
      # Configura o Usuário do Banco de Dados
      - MB_DB_USER=postgres
      # Configura a Senha do Banco de Dados
      - MB_DB_PASS=SENHA
    deploy:
      # Define o modo de deploy do Metabase
      mode: replicated
      # Define o número de réplicas do Metabase
      replicas: 1
      # Define a estratégia de deploy do Metabase
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:
          # Define a quantidade de CPU para para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para para evitar travamento do Host
          memory: 2048M
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Configura o endereço do Metabase
        - traefik.http.routers.metabase.rule=Host(`reports.agenciasynca.com.br`)
        # Configura o SSL do Metabase
        - traefik.http.routers.metabase.entrypoints=websecure
        # Configura o Certificado SSL do Metabase
        - traefik.http.routers.metabase.tls.certresolver=letsencryptresolver
        # Configura o serviço do Metabase
        - traefik.http.routers.metabase.service=metabase
        # Configura a porta do serviço do Metabase
        - traefik.http.services.metabase.loadbalancer.server.port=3000
        # Habilita o passHostHeader do Metabase
        - traefik.http.services.metabase.loadbalancer.passHostHeader=true

networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
