version: "3.7"

services:
  # Define a service named minio
  minio:
    # Usa a imagem do MinIO no Quay.io
    image: quay.io/minio/minio
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # Define o Comando de inicio do servidor do Minio
    command: server /data --console-address ":9001"
    # Define a rede que o container vai usar
    networks:
      - network_swarm_public
    # Define o volume que irá armazenar os dados do minio
    volumes:
      - minio_data:/data
      # /mnt/VOLUME/minio:/data
    # Define as variaveis de ambiente que o container vai usar
    environment:
      # Define o usuario root do Minio
      - MINIO_ROOT_USER=ZwIJv7DO2bZoQV8hpe51
      # Define a senha root do Minio
      - MINIO_ROOT_PASSWORD=l7YKI7ptN8BxqWCm1uKV
      # Define o endereço do console do Minio
      - MINIO_BROWSER_REDIRECT_URL=https://minioconsole.agenciasynca.com.br
      # Define o endereço público do Minio
      - MINIO_SERVER_URL=https://s3.agenciasynca.com.br
    deploy:
      # Define o modo de deploy do container
      mode: replicated
      # Define o numero de replicas do container (sempre 1)
      replicas: 1
      # Define o local de execução do container
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:
          # Define a quantidade de CPU para o CodeChat para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o CodeChat para evitar travamento do Host
          memory: 1024M
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Define o endereço publico do Minio
        - traefik.http.routers.minio_public.rule=Host(`s3.agenciasynca.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.minio_public.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.minio_public.tls.certresolver=letsencryptresolver
        # Define a porta do servidor publico do Minio
        - traefik.http.services.minio_public.loadbalancer.server.port=9000
        # Define os Headers que o Minio vai usar
        - traefik.http.services.minio_public.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.minio_public.service=minio_public
        # Define o endereço do console do Minio
        - traefik.http.routers.minio_console.rule=Host(`minioconsole.agenciasynca.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.minio_console.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.minio_console.tls.certresolver=letsencryptresolver
        # Define a porta do servidor do console do Minio
        - traefik.http.services.minio_console.loadbalancer.server.port=9001
        # Define os Headers que o Minio vai usar
        - traefik.http.services.minio_console.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.minio_console.service=minio_console

# Definição dos Volumes do Stack
volumes:
  minio_data:
    external: true
    name: minio_data

# Definição dos Network do Stack
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
