version: "3.7"
# Definição dos Serviços
services:
  # Definição do Serviço do Worker
  n8n_webhook:
    # imagem do docker
    image: n8nio/n8n:latest
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # comando padrão para subir o servidor web
    command: webhook
    # configura a rede do serviço
    networks:
      - network_swarm_public
    # configura as variáveis de ambiente
    environment:

    # Configura o Modo de Deploy da Aplicação
    deploy:
      # O editor será executado no modo de replicação
      mode: replicated
      # Vamos ter apenas uma instância do editor
      replicas: 2
      # Configura o local de execução
      placement:
        # Você pode rodar o Editor no Manager mesmo pois usa poucos recursos
        constraints:
          - node.role == manager
          # - node.hostname == worker1
          # - node.labels.app == workers # nome do label: app, valor do label: workers
      resources:
        # Definição dos Limites de Recursos deste Serviço
        limits:
          # Define a quantidade de CPU para o N8N para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o N8N para evitar travamento do Host
          memory: 1024M
      # Define os Labels do Serviço
      labels:
        # Configura o Roteamento do Traefik
        - traefik.enable=true
        # Define o enderço do Webhook do N8N
        - traefik.http.routers.n8n_webhook.rule=Host(`webhooks.synca.com.br`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        # Define o serviço do Webhook
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        # Define a porta do serviço do Webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
        # Define o uso do Host Header
        - traefik.http.services.n8n_webhook.loadbalancer.passHostHeader=true
      # Configura o modo de atualização do serviço
      update_config:
        # Configura o paralelismo de atualização
        parallelism: 1
        # Configura o tempo de espera entre as atualizações
        delay: 30s
        # Configura a ação em caso de falha
        order: start-first
        # Configura a ação em caso de falha
        failure_action: rollback
networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
