version: "3.7"
# definição dos serviços do stack
services:
  # definição dos Serviços
  qdrant:
      # define a imagem do qdrant
    image: qdrant/qdrant:latest
    # Define o Hostname
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # configura a rede do serviço
    networks:
      - network_swarm_public
    # Define os volumes do qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    # Variáveis de Ambiente do qdrant
    environment:
      - QDRANT__SERVICE__ENABLE_TLS=false
      - QDRANT__SERVICE__API_KEY=sua_api_key
    # Configura o Modo de Deploy da Aplicação
    deploy:
      # O editor será executado no modo de replicação
      mode: replicated
      # Vamos ter apenas uma instância do editor
      replicas: 1
      # Configura o local de execução
      placement:
        constraints:
          # Você pode rodar o Editor no Manager mesmo pois usa poucos recursos
          - node.role == manager
          # - node.hostname == worker1
      # Limitação
      resources:
        # Definição dos Limites de Recursos deste Serviço
        limits:
          # Define a quantidade de CPU para o N8N para evitar travamento do Host
          cpus: "2"
          # Define a quantidade de RAM para o N8N para evitar travamento do Host
          memory: 2048M

# Define os Volumes
volumes:
  qdrant_data:
    external: true
    name: qdrant_data

# Define as Redes
networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
