version: "3.7"

##############
#
# Para configurar o chatwoot, execute o comando abaixo no console do container:
#
# bundle exec rails db:chatwoot_prepare
#
# Variáveis de Ambiente:
#
# https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables
#
#############

# Definição dos Serviços
services:
  # Definição do Nome do Serviço de Background
  chatwoot_sidekiq:
    # imagem oficial do chatwoot
    image: chatwoot/chatwoot:latest
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # comando padrão para subir o servidor web
    command: bundle exec sidekiq -C config/sidekiq.yml
    # configura os volumes do chatwoot (compartilhado)
    volumes:
      - chatwoot_data:/app/storage # arquivos do usuário
    # configura a rede do serviço
    networks:
      - network_swarm_public
    # Configura as variáveis de ambiente do chatwoot
    environment:

    deploy:
      mode: replicated # sempre como replicated
      replicas: 1 # geralmente somente 1 réplica
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:
          # Define a quantidade de CPU para o CodeChat para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o CodeChat para evitar travamento do Host
          memory: 1024M

volumes:
  chatwoot_data:
    external: true
    name: chatwoot_data

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
