version: "3.7"

services:
  # Define o Serviço do Cal
  calcom:
    # Define a imagem do Cal
    # https://github.com/calcom/docker/releases
    image: calcom/cal.com:v4.4.2
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # Define a Rede do Docker
    networks:
      - network_swarm_public
    # Define as Variáveis de Ambiente
    environment:
      # Variáveis Genéricas
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - LICENSE=agree
      # Define o modo de execução do node
      - NODE_ENV=production
      # Define a SecretKey do Cal
      - NEXTAUTH_SECRET=l94huAwLcuiVHYtl9doZaTZfUpeQWPeS
      - CALENDSO_ENCRYPTION_KEY=jiefKFQ2wqlRyT0gwBJujknMvWEI2j77
      # Define os Endereços do Cal
      - NEXT_PUBLIC_WEBAPP_URL=https://cal.agenciasynca.com.br
      - NEXTAUTH_URL=https://cal.agenciasynca.com.br
      - NEXT_PUBLIC_API_V2_URL=http://localhost:5555/api/v2
      - NEXT_PUBLIC_CONSOLE_URL=https://cal.agenciasynca.com.br
      - NEXT_PUBLIC_WEBSITE_URL=https://cal.agenciasynca.com.br
      - WEB_APP=https://cal.agenciasynca.com.br
      # Define as Variáveis de Banco de Dados
      - DATABASE_URL=postgresql://postgres:SENHA@postgres:5432/calcom8xhb9xh`
      # Definição da Variável para conexão direta com o banco de dados
      - DATABASE_DIRECT_URL=postgresql://postgres:SENHA@postgres:5432/calcom8xhb9xh
    # Configura o Modo de Deploy da Aplicação
    deploy:
      # Configura o modo de deploy
      mode: replicated
      # Configura o numero de replicas
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      resources:
        limits:
          # Define a quantidade de CPU para o cal para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o cal para evitar travamento do Host
          memory: 1024M
      # Define as Configurações do Traefik
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Define o Endereço do Cal
        - traefik.http.routers.calcom.rule=Host(`cal.agenciasynca.com.br`)
          # Define o tipo de entrada para HTTPS
        - traefik.http.routers.calcom.entrypoints=websecure
        # Define o certificado
        - traefik.http.routers.calcom.tls.certresolver=letsencryptresolver
        # Define o serviço do Cal
        - traefik.http.routers.calcom.service=calcom
        # Define a porta do Cal
        - traefik.http.services.calcom.loadbalancer.server.port=3000
        # Define os Headers do Cal
        - traefik.http.services.calcom.loadbalancer.passHostHeader=true

networks:
  network_swarm_public:
    name: network_swarm_public
    external: true
