version: "3.7"

services:
  # Define a serviço Viewer
  typebot_viewer:
    # Usa a imagem do Typebot Viewer
    # https://hub.docker.com/r/baptistearno/typebot-viewer/tags
    image: baptistearno/typebot-viewer:2
    # Define o hotname do container
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    # Define a rede que o container vai usar
    networks:
      - network_swarm_public
    # Define as variaveis de ambiente que o container vai usar
    environment:

    deploy:
      # Define o modo de deploy do container
      mode: replicated
      # Define o numero de replicas do container (sempre 1)
      replicas: 1
      # Define o local de execução do container
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      # Define os limites de recursos do container
      resources:
        limits:
          # Define a quantidade de CPU para o Typebot para evitar travamento do Host
          cpus: "1"
          # Define a quantidade de RAM para o Typebot para evitar travamento do Host
          memory: 1024M
      # Define as labels do container
      labels:
        # Habilita o Traefik
        - traefik.enable=true
        # Define o endereço publico do Typebot
        - traefik.http.routers.typebot_viewer.rule=Host(`meubot.luizeof.dev`)
        # Redireciona o endereço para HTTPS
        - traefik.http.routers.typebot_viewer.entrypoints=websecure
        # Define o certificado SSL
        - traefik.http.routers.typebot_viewer.tls.certresolver=letsencryptresolver
        # Define a porta do servidor publico do Typebot
        - traefik.http.services.typebot_viewer.loadbalancer.server.port=3000
        # Define os Headers que o Typebot vai usar
        - traefik.http.services.typebot_viewer.loadbalancer.passHostHeader=true
        # Define o serviço que irá ser usado
        - traefik.http.routers.typebot_viewer.service=typebot_viewer

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
